### ISSUE TITLE
Error when adding more than one creator

### ISSUE THREAD

**Issue by cacosta88** [BuidlGuidl/LaunchPod#48]
## Issue

Error message when adding more than one creator

## Error message

When adding more than one creator as follows: 

![image](https://github.com/BuidlGuidl/LaunchPod/assets/58862302/2f931ecb-bd00-45a4-92c5-61d9513f6f7c)

The creators are properly added at the level of the smart contract, but the following error message pops-up:

![image](https://github.com/BuidlGuidl/LaunchPod/assets/58862302/552bc89a-ef0d-4665-ae50-4f9eb7f055c1)

**Comment by ZakGriffith** [comment]
I had this error as well, but only the first creator in the list was added.

**Comment by ZakGriffith** [comment]
Fixed in #56
