### ISSUE TITLE
Pre-loading creators and caps upon deployment fails if deployer is not admin

### ISSUE THREAD

**Issue by cacosta88** [BuidlGuidl/LaunchPod#77]
In  `01_deploy_your_contract.ts`, if the first arguments in args in the deploy function is not deployer, contract will fail do deploy if creators are pre-loaded for deployment in the 4th (list of creators) and 5th(list of caps) arguments. Thinking out loud here, I think there a few ways to handle this:

1. Disable preloading creators (simpler)
2. Allow deployer the ability to do an one off creator addition on deployment only (more complex)
3. Leave as is, make sure deployer is admin if pre-loading creators (simplest)

**Comment by ZakGriffith** [comment]
Fixed in #80
